export const themes = {
  cutie: {
    name: 'Cutie Light™',
    font: "font-['Quicksand']",
    bg: "bg-gradient-to-br from-pink-100 via-purple-100 to-blue-100",
    text: "text-gray-800",
    card: "bg-white text-black rounded-2xl shadow-md",
    cardHover: "hover:scale-105 hover:shadow-lg transition-transform duration-200",
    effectText: "text-pink-500 font-semibold",
    sidebarBg: "bg-pink-50 border border-pink-200",
    thankYou: "text-xs text-gray-400 italic",
    charity: "text-xs text-pink-500 italic",
    logo: "/ceoio-logo.png",
    favicon: "/favicon-cutie.png",
  },
  grindset: {
    name: 'Dark Grindset™',
    font: "font-['Inter']",
    bg: "bg-gradient-to-br from-gray-900 via-gray-800 to-black",
    text: "text-white",
    card: "bg-gray-800 text-white rounded-xl shadow-lg",
    cardHover: "hover:scale-105 hover:shadow-2xl transition-transform duration-200",
    effectText: "text-green-400 font-bold",
    sidebarBg: "bg-gray-900 border border-gray-700",
    thankYou: "text-xs text-gray-500 italic",
    charity: "text-xs text-green-400 italic",
    logo: "/ceoio-logo-dark.png",
    favicon: "/favicon-grindset.png",
  },
};
